server:
  servlet:
    context-path : /tienda
# H2
spring:
  h2:
    console:
      enabled : true
    console.path : /h2
# Datasource
  datasource:
    url : jdbc:h2:file:~/formacion_salamanca
    username : sa
    password : 
    driver-class-name : org.h2.Driver
#JPA
  jpa:    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:      ddl-auto: create-drop